# Generated by Django 5.0.7 on 2024-08-09 14:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('short_descr', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Short Description')),
                ('descr', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Full Description')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.language', verbose_name='Localization')),
            ],
            options={
                'verbose_name': ('Localized Information',),
                'verbose_name_plural': 'Localized Information',
            },
        ),
    ]
