# Generated by Django 5.0.7 on 2024-08-13 15:29

import django.db.models.deletion
import travels.services.file_uploader
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('travels', '0002_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Localized Information', 'verbose_name_plural': 'Localized Information'},
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('type', models.CharField(choices=[('main', 'main'), ('extra', 'extra')], max_length=5, verbose_name='Type')),
                ('file', models.ImageField(upload_to=travels.services.file_uploader.FileUploader('images'), verbose_name='File')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
