# Generated by Django 5.0.7 on 2024-08-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_info_options_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
            ],
            options={
                'verbose_name': 'Extra Image',
                'verbose_name_plural': 'Extra Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('travels.image',),
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
            ],
            options={
                'verbose_name': 'Main Image',
                'verbose_name_plural': 'Main Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('travels.image',),
        ),
    ]
