# Generated by Django 5.0.7 on 2024-08-14 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_placetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Longitude')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.city', verbose_name='City')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.placetype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'default_related_name': 'places',
            },
        ),
    ]
