# Generated by Django 5.0.7 on 2024-08-14 15:47

import travels.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=7, validators=[travels.validators.GPSCoordinateValidator('latitude')], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[travels.validators.GPSCoordinateValidator('longitude')], verbose_name='Longitude'),
        ),
    ]
