# Generated by Django 5.0.7 on 2024-08-15 13:17

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rout',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Rout',
                'verbose_name_plural': 'Routs',
                'default_related_name': 'routs',
            },
        ),
    ]
