# Generated by Django 5.0.7 on 2024-08-15 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_rout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutPoint',
            fields=[
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.place', verbose_name='Place')),
                ('rout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='travels.rout', verbose_name='Rout')),
            ],
            options={
                'verbose_name': 'Rout Point',
                'verbose_name_plural': 'Rout Points',
                'ordering': ['ordering'],
                'abstract': False,
                'default_related_name': 'rout_points',
            },
        ),
    ]
