# Generated by Django 5.0.7 on 2024-08-17 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_routpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Picked'), (2, 'In process'), (3, 'Completed'), (4, 'Canceled')], default=1, verbose_name='Status')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.routpoint', verbose_name='Last Point')),
                ('rout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.rout', verbose_name='Chosen Rout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
                'default_related_name': 'journeys',
            },
        ),
    ]
