# Generated by Django 5.0.7 on 2024-08-19 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='descr',
        ),
        migrations.AddField(
            model_name='info',
            name='full_descr',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4096)], verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='info',
            name='short_descr',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2048)], verbose_name='Short Description'),
        ),
    ]
